KadroMaster/KadroMaster/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("MainApp.urls")),
]

KadroMaster/MainApp/urls.py
from django.urls import path
from MainApp.views import *
from django.contrib.auth.views import LogoutView

urlpatterns = [
    path('', profile_hr, name="profile"),
    path('login/', auth_hr, name="login"),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('department/', department_hr, name="department"),
    path('job/', job_hr, name="job"),
    path('change-password/', password_hr, name="password"),
    path('personal/', personal_hr, name="personal"),
    path('api/job-titles/', get_job_titles, name='get_job_titles'),
    path('time-tracking/', time_tracking_hr, name="time-tracking"),
    path('info-personal/<id>/', info_personal_hr, name="info-personal"),
    path('salary/<id>/', salary_hr, name="salary"),
    path('groups/', groups_admin, name="groups"),
    path('users/', users_admin, name="users"),
    path('stats/', stats_hr, name="stats"),
    path('api/stats/', get_stats_employee, name='get_stats_employee'),
]

KadroMaster/MainApp/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.core.validators import MinLengthValidator

class Groups(models.Model):
    title = models.CharField(max_length=150)
    access_for_emplyees = models.IntegerField(default=0)
    access_for_departments = models.IntegerField(default=0)
    access_for_jobs = models.IntegerField(default=0)
    access_for_reports = models.IntegerField(default=0)
    access_for_time = models.IntegerField(default=0)

class Departments(models.Model):
    title = models.CharField(max_length=150, unique=True)

class Jobs(models.Model):
    title = models.CharField(max_length=150)
    salary_per_hour = models.DecimalField(max_digits=10, decimal_places=2)
    departament = models.ForeignKey(Departments, on_delete=models.DO_NOTHING)

class Employees(models.Model):
    male = 'm'
    female = 'f'
    genders = (
        (male, male),
        (female, female),
    )
    fullname = models.CharField(max_length=150)
    personnel_number = models.CharField(max_length=6, validators=[MinLengthValidator(6)], unique=True)
    gender = models.CharField(max_length=1, choices=genders)
    birthday = models.DateField()
    residence_address = models.CharField(max_length=255)
    phone = models.CharField(max_length=20)
    email = models.CharField(max_length=100, null=True)
    employment_date = models.DateField()
    passport = models.CharField(max_length=10, validators=[MinLengthValidator(10)])
    individual_tax_number = models.CharField(max_length=12, validators=[MinLengthValidator(12)])
    insurance_number = models.CharField(max_length=11, validators=[MinLengthValidator(11)])
    work_book_number = models.CharField(max_length=7, validators=[MinLengthValidator(7)])
    military_ticket = models.CharField(max_length=7, validators=[MinLengthValidator(7)], null=True)
    job = models.ForeignKey(Jobs, on_delete=models.DO_NOTHING)

class User(AbstractUser):
    password = models.CharField(("password"), max_length=128)
    username = models.CharField(max_length=150, unique=True)
    group = models.ForeignKey(Groups, on_delete=models.DO_NOTHING, null=True)
    employee = models.ForeignKey(Employees, on_delete=models.CASCADE, null=True)

class TimeTraking(models.Model):
    date = models.DateField()
    amount = models.IntegerField()
    employee = models.ForeignKey(Employees, on_delete=models.CASCADE)

class Salary(models.Model):
    salary_date = models.DateField()
    number_of_hours_worked = models.CharField(max_length=20)
    final_salary = models.DecimalField(max_digits=10, decimal_places=2)
    employee = models.ForeignKey(Employees, on_delete=models.CASCADE)

class AccessControl(models.Model):
    date = models.DateTimeField()
    state = models.CharField(max_length=100)
    employee = models.ForeignKey(Employees, on_delete=models.CASCADE)

KadroMaster/MainApp/forms.py
from django import forms
from django.forms import ModelForm
from MainApp.models import *
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.password_validation import validate_password
from django.core.exceptions import ValidationError

class LoginForm(forms.Form):
    username = forms.CharField(max_length=100)
    password = forms.CharField(widget=forms.PasswordInput())

class CustomPasswordChangeForm(PasswordChangeForm):
    old_password = forms.CharField(
        label="Текущий пароль",
        widget=forms.PasswordInput(attrs={
            'class': 'form-control',
            'placeholder': 'Введите текущий пароль',
            'id': 'id_old_password'
        }),
        strip=False,
    )
    
    new_password1 = forms.CharField(
        label="Новый пароль",
        widget=forms.PasswordInput(attrs={
            'class': 'form-control',
            'placeholder': 'Введите новый пароль',
            'id': 'id_new_password1'
        }),
        strip=False,
        help_text="Пароль должен содержать не менее 8 символов и не быть слишком простым.",
    )
    
    new_password2 = forms.CharField(
        label="Подтверждение нового пароля",
        widget=forms.PasswordInput(attrs={
            'class': 'form-control',
            'placeholder': 'Повторите новый пароль',
            'id': 'id_new_password2'
        }),
        strip=False,
    )

    def clean_new_password1(self):
        password1 = self.cleaned_data.get('new_password1')
        try:
            validate_password(password1, self.user)
        except ValidationError as error:
            self.add_error('new_password1', error)
        return password1

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['old_password'].widget.attrs.update({'autofocus': True})

class AddEmployee(ModelForm):
    class Meta:
        model = Employees
        fields = ['fullname', 'gender', 'birthday', 'residence_address', 'phone', 'employment_date', 'passport', 'email',
                  'individual_tax_number', 'insurance_number', 'work_book_number', 'job']

KadroMaster/MainApp/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from MainApp.models import *
from MainApp.forms import *
from django.db.models import Q, F, Count, Sum
from django.http import JsonResponse
import random, datetime, calendar
from passlib.hash import django_pbkdf2_sha256
from django.utils import timezone
from django.db import connection
from datetime import date, datetime, timedelta, time
from collections import defaultdict

def profile_hr(request):
    departments = Departments.objects.all()
    if not request.user.is_authenticated:
        return redirect("login")
    
    try:
        if request.user.group.access_for_emplyees == 1 or request.user.is_superuser == 1:
            employeers = Employees.objects.all()
        else:
            employeers = Employees.objects.filter(job__departament_id=request.user.employee.job.departament.id)
            departments = Departments.objects.filter(id=request.user.employee.job.departament.id)
    except:
        employeers = Employees.objects.all()
    if request.method == 'POST':
        if request.GET.get("delete") is not None:
            Employees.objects.filter(id=request.GET.get("delete")).delete()
            return redirect("profile")
        try:
            if request.POST.get('fullname') and request.POST.get('p_number'):
                employeers = Employees.objects.filter(Q(fullname__contains=request.POST.get('fullname')) & Q(personnel_number__contains=request.POST.get('p_number')))
            elif request.POST.get('fullname'):
                employeers = Employees.objects.filter(fullname__contains=request.POST.get('fullname'))
            elif request.POST.get('departament_id'):
                employeers = Employees.objects.filter(job__departament_id=request.POST.get('departament_id'))
            else:
                employeers = Employees.objects.filter(personnel_number__contains=request.POST.get('p_number'))
        except:
            pass

    return render(request, 'MainApp/main.html', {'employeers': employeers, 'departments': departments})

def auth_hr(request):
    if request.user.is_authenticated:
        return redirect('profile')

    users = User.objects.filter(password__isnull=False)
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('profile')
            else:
                error_message = "Неправильный пароль!"
                return render(request, 'MainApp/login.html', {'error_message': error_message, 'users': users})

    return render(request, 'MainApp/login.html', {'users': users})

def department_hr(request):
    departments = Departments.objects.annotate(employee_count=Count('jobs__employees')).prefetch_related('jobs_set')
    if not request.user.is_authenticated:
        return redirect("login")
    
    if request.method == 'POST':
        if 'add' in request.POST:
            department_new = Departments()
            department_new.title = request.POST.get('title')
            try:
                department_new.save()
            except:
                return render(request, 'MainApp/department.html', {'departments': departments, 'error': 'Данный отдел уже существует'})
        elif 'find' in request.POST:
            departments = Departments.objects.filter(title__contains=request.POST.get('title')).annotate(employee_count=Count('jobs__employees')).prefetch_related('jobs_set')
        elif 'delete' in request.GET:
            count_of_jobs = Jobs.objects.filter(departament=Departments.objects.filter(id=request.GET.get("delete")).first()).count()
            if count_of_jobs == 0:
                Departments.objects.filter(id=request.GET.get("delete")).delete()
            else:
                return render(request, 'MainApp/department.html', {'departments': departments, 'error': 'Необходимо удалить все должности'})
    return render(request, 'MainApp/department.html', {'departments': departments})

def job_hr(request):
    departments = Departments.objects.all()
    jobs = Jobs.objects.all().prefetch_related('employees_set')
    if not request.user.is_authenticated:
        return redirect("login")
    
    if request.method == 'POST':
        if 'add' in request.POST:
            job_new = Jobs()
            job_new.title = request.POST.get('title')
            job_new.salary_per_hour = request.POST.get('salary_per_hour')
            job_new.departament = Departments.objects.filter(id=request.POST.get('departament_id')).first()
            try:
                job_new.save()
            except:
                pass
        elif 'find' in request.POST:
            filter_params = {
            'title__contains': request.POST.get('title'),
            'salary_per_hour__contains': request.POST.get('salary_per_hour'),
            'departament_id': request.POST.get('departament_id'),
            }
            filter_params = {k: v for k, v in filter_params.items() if v is not None}
            jobs = Jobs.objects.filter(**filter_params).prefetch_related('employees_set')
        elif 'delete' in request.GET:
            try:
                Jobs.objects.filter(Q(id=request.GET.get("delete"))).delete()
            except:
                return render(request, 'MainApp/job.html', {'departments': departments, 'jobs': jobs, 'error': 'Необходимо уволить всех сотрудников на должности'})
    return render(request, 'MainApp/job.html', {'departments': departments, 'jobs': jobs})

def password_hr(request):
    if not request.user.is_authenticated:
        return redirect("login")
    
    if request.method == 'POST':
        form = CustomPasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            form.save()
            return redirect('profile')
    else:
        form = CustomPasswordChangeForm(request.user)
    return render(request, 'MainApp/password.html', {'form': form})

def personal_hr(request):
    if not request.user.is_authenticated:
        return redirect("login")
    departments = Departments.objects.all()

    if request.method == 'POST':
        form = AddEmployee(request.POST)
        if form.is_valid():
            db = form.save(commit=False)
            if request.POST['military_ticket']:
                db.military_ticket = request.POST['military_ticket']
            db.personnel_number = random.randint(100000,999999)
            db.save()
    return render(request, 'MainApp/personal.html', {'departments': departments})

def get_job_titles(request):
    department_id = request.GET.get('department')
    if department_id:
        jobs = Jobs.objects.filter(departament_id=department_id)
    else:
        jobs = Jobs.objects.none()
    
    data = [{'id': job.id, 'title': job.title} for job in jobs]
    return JsonResponse(data, safe=False)

def time_tracking_hr(request):
    if not request.user.is_authenticated:
        return redirect("login")
    employeers = Employees.objects.filter(job__departament_id=request.user.employee.job.departament.id)
    time_tracking = TimeTraking.objects.filter(employee__job__departament_id=request.user.employee.job.departament.id).order_by('-date')
    if request.method == 'POST':
        if 'add' in request.POST:
            time_tracking_new = TimeTraking()
            time_tracking_new.date = request.POST.get('date')
            time_tracking_new.amount = request.POST.get('amount')
            time_tracking_new.employee = Employees.objects.filter(id=request.POST.get('employee')).first()
            try:
                time_tracking_new.save()
            except:
                pass
        elif 'find' in request.POST:
            filter_params = {
            'date': request.POST.get('date'),
            'amount': request.POST.get('amount'),
            'employee_id': request.POST.get('employee'),
            }
            filter_params = {k: v for k, v in filter_params.items() if v is not None and v != ''}
            time_tracking = TimeTraking.objects.filter(**filter_params).filter(employee__job__departament_id=request.user.employee.job.departament.id).order_by('-date')
        elif 'delete' in request.GET:
            TimeTraking.objects.filter(id=request.GET.get("delete")).delete()
    return render(request, 'MainApp/time_tracking.html', {'employeers': employeers, 'time_tracking': time_tracking})

def info_personal_hr(request, id):
    if not request.user.is_authenticated:
        return redirect("login")
    departments = Departments.objects.all()
    employee = Employees.objects.filter(id=id).first()
    if request.method == 'POST':
        if 'new' in request.POST:
            if request.POST.get('job') is not None:
                employee.job = Jobs.objects.filter(id=request.POST.get('job')).first()
            employee.fullname = request.POST.get('fullname')
            employee.birthday = request.POST.get('birthday')
            employee.gender = request.POST.get('gender')
            employee.phone = request.POST.get('phone')
            employee.residence_address = request.POST.get('residence_address')
            employee.passport = request.POST.get('passport')
            employee.insurance_number = request.POST.get('insurance_number')
            employee.individual_tax_number = request.POST.get('individual_tax_number')
            employee.work_book_number = request.POST.get('work_book_number')
            employee.military_ticket = request.POST.get('military_ticket')
            employee.email = request.POST.get('email')
            employee.employment_date = request.POST.get('employment_date')
            employee.save()
            return redirect("info-personal", id=id)

KadroMaster/MainApp/templates/MainApp/add_user.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Создание пользователей</title>

    <!-- Подключение jQuery и Select2 -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>

    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f7f7f7;
        }
        .header {
            background-color: #FFB300;
            color: white;
            padding: 15px;
            display: flex;
            justify-content: space-between;
            align-items: center;
        }
        .header .menu {
            display: flex;
            gap: 20px;
        }
        .header .menu a {
            color: white;
            text-decoration: none;
            font-weight: bold;
        }
        .container {
            padding: 20px;
        }
        .user-form {
            background-color: white;
            padding: 20px;
            border-radius: 5px;
            box-shadow: 0 2px 5px rgba(0,0,0,0.1);
            margin-bottom: 20px;
        }
        .form-row {
            display: flex;
            gap: 15px;
            margin-bottom: 15px;
        }
        .form-group {
            flex: 1;
        }
        .form-group label {
            display: block;
            margin-bottom: 5px;
            font-weight: bold;
            color: #555;
        }
        .form-group input, 
        .form-group select {
            width: 100%;
            padding: 10px;
            border: 1px solid #ccc;
            border-radius: 5px;
            box-sizing: border-box;
        }
        .form-actions {
            text-align: right;
            margin-top: 20px;
        }
        .form-actions button {
            padding: 10px 20px;
            background-color: #FFB300;
            color: white;
            border: none;
            border-radius: 5px;
            cursor: pointer;
            font-weight: bold;
        }
        .form-actions button:hover {
            background-color: #E59400;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }
        table, th, td {
            border: 1px solid #ddd;
        }
        th, td {
            padding: 10px;
            text-align: left;
        }
        th {
            background-color: #f2f2f2;
        }
        td {
            background-color: #e0e0e0;
        }
        .logout {
            background-color: #FFB300;
            color: white;
            padding: 10px 20px;
            text-decoration: none;
            border: none;
            cursor: pointer;
            border-radius: 5px;
            transition: background-color 0.3s;
        }
        .logout:hover {
            background-color: #E59400;
        }
        .delete-btn {
            padding: 5px 10px;
            background-color: #ff3333;
            color: white;
            border: none;
            border-radius: 3px;
            cursor: pointer;
        }
        .delete-btn:hover {
            background-color: #cc0000;
        }
        .select2-container--default .select2-selection--single {
            height: 42px;
            padding: 6px 10px;
            font-size: 16px;
            border-radius: 5px;
            border: 1px solid #ccc;
        }
    </style>
</head>
<body>
    <div class="header">
        <div class="menu">
            <label>КадроМастер</label>
            <a href="{% url 'profile' %}">Назад</a>
        </div>
        <form method="post" action="{% url 'logout' %}?next=/">
            {{ user.username }}
            {% csrf_token %}
            <button class="logout" type="submit">Выйти</button>
        </form>
    </div>

    <div class="container">
        <div class="user-form">
            <h2>Создать нового пользователя</h2>
            <form method="post">
                {% csrf_token %}
                <div class="form-row">
                    <div class="form-group">
                        <label for="employee">Сотрудник:</label>
                        <select id="employee" name="employee" required>
                            <option value="" disabled selected>Сотрудник</option>
                            {% for employee in employees %}
                            <option value="{{ employee.id }}">{{ employee.fullname }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="password">Пароль:</label>
                        <input type="password" id="password" name="password" required>
                    </div>
                </div>

                <div class="form-row">
                    <div class="form-group">
                        <label for="role">Роль:</label>
                        <select id="role" name="role" required>
                            <option value="" disabled selected>Выберите роль</option>
                            {% for group in groups %}
                            <option value="{{ group.id }}">{{ group.title }}</option>
                            {% endfor %}
                        </select>
                    </div>
                </div>

                <div class="form-actions">
                    <button type="submit" name="create_user">Создать пользователя</button>
                </div>
            </form>
        </div>

        <table>
            <thead>
                <tr>
                    <th>ФИО</th>
                    <th>Роль</th>
                    <th>Дата создания</th>
                    <th>Действия</th>
                </tr>
            </thead>
            <tbody>
                {% for user in users %}
                <tr>
                    <td>{{ user.username }}</td>
                    {% if user.is_superuser == 1 %}
                    <td>Superadmin</td>
                    {% else %}
                    <td>{{ user.group.title }}</td>
                    {% endif %}
                    <td>{{ user.date_joined|date:"d.m.Y" }}</td>
                    <td>
                        <form action="{% url 'users' %}?delete={{ user.id }}" method="post">
                            {% csrf_token %}
                            <button type="submit" class="delete-btn">Удалить</button>
                        </form>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

    <script>
        $(document).ready(function() {
            $('#employee').select2({
                placeholder: "Выберите сотрудника",
                width: '100%',
                language: {
                    noResults: function() {
                        return "Совпадений не найдено";
                    }
                }
            });
        });
    </script>
</body>
</html>

KadroMaster/MainApp/templates/MainApp/groups_for_users.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Управление доступами</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f7f7f7;
        }
        .header {
            background-color: #FFB300;
            color: white;
            padding: 15px;
            display: flex;
            justify-content: space-between;
            align-items: center;
        }
        .header .menu {
            display: flex;
            gap: 20px;
        }
        .header .menu a {
            color: white;
            text-decoration: none;
            font-weight: bold;
        }
        .container {
            padding: 20px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }
        table, th, td {
            border: 1px solid #ddd;
        }
        th, td {
            padding: 10px;
            text-align: left;
        }
        th {
            background-color: #f2f2f2;
        }
        .logout {
            background-color: #FFB300;
            color: white;
            padding: 10px 20px;
            text-decoration: none;
            border: none;
            cursor: pointer;
            transition: background-color 0.3s;
        }
        .logout:hover {
            background-color: #E59400;
        }
        .role-form {
            background-color: white;
            padding: 20px;
            border-radius: 5px;
            box-shadow: 0 2px 5px rgba(0,0,0,0.1);
            margin-bottom: 20px;
        }
        .role-form h2 {
            margin-top: 0;
            color: #333;
        }
        .form-group {
            margin-bottom: 15px;
        }
        .form-group label {
            display: block;
            margin-bottom: 5px;
            font-weight: bold;
            color: #555;
        }
        .form-group input {
            width: 100%;
            padding: 8px;
            box-sizing: border-box;
            border: 1px solid #ddd;
            border-radius: 4px;
        }
        .form-actions {
            text-align: right;
        }
        .form-actions button {
            padding: 8px 15px;
            background-color: #FFB300;
            color: white;
            border: none;
            border-radius: 4px;
            cursor: pointer;
            font-weight: bold;
        }
        .form-actions button:hover {
            background-color: #E59400;
        }
        .checkbox-group {
            display: flex;
            flex-wrap: wrap;
            gap: 15px;
            margin-top: 10px;
        }
        .checkbox-item {
            display: flex;
            align-items: center;
        }
        .checkbox-item input {
            margin-right: 5px;
        }
        .actions button {
            padding: 5px 10px;
            background-color: #FFB300;
            color: white;
            border: none;
            border-radius: 4px;
            cursor: pointer;
            margin-right: 5px;
        }
        .actions button:hover {
            background-color: #E59400;
        }
    </style>
</head>
<body>
    <div class="header">
        <div class="menu">
            <label>КадроМастер</label>
            <a href="{% url 'profile' %}">Назад</a>
        </div>
        <form method="post" action="{% url 'logout' %}?next=/">
            {{ user.username }}
            {% csrf_token %}
            <button class="logout" type="submit">Выйти</button>
        </form>
    </div>
    <div class="container">
        <div class="role-form">
            <h2>Добавить новую роль</h2>
            <form method="post">
                {% csrf_token %}
                <div class="form-group">
                    <label for="role-name">Название роли:</label>
                    <input type="text" id="role-name" name="role-name" required placeholder="Введите название роли">
                </div>
                
                <div class="form-group">
                    <label>Разрешения:</label>
                    <div class="checkbox-group">
                        <div class="checkbox-item">
                            <input type="checkbox" id="perm-personal" name="personal" value="1">
                            <label for="perm-personal">Управление сотрудниками</label>
                        </div>
                        <div class="checkbox-item">
                            <input type="checkbox" id="perm-department" name="department" value="1">
                            <label for="perm-department">Управление отделами</label>
                        </div>
                        <div class="checkbox-item">
                            <input type="checkbox" id="perm-job" name="job" value="1">
                            <label for="perm-job">Управление должностями</label>
                        </div>
                        <div class="checkbox-item">
                            <input type="checkbox" id="perm-reports" name="reports" value="1">
                            <label for="perm-reports">Создание отчетов</label>
                        </div>
                        <div class="checkbox-item">
                            <input type="checkbox" id="perm-reports" name="time" value="1">
                            <label for="perm-reports">Учет рабочего времени</label>
                        </div>
                    </div>
                </div>
                
                <div class="form-actions">
                    <button type="submit" name="add">Создать роль</button>
                </div>
            </form>
        </div>

        <table>
            {{ error }}
            <thead>
                <tr>
                    <th>Название роли</th>
                    <th>Управление сотрудниками</th>
                    <th>Управление отделами</th>
                    <th>Управление должностями</th>
                    <th>Создание отчетов</th>
                    <th>Учет рабочего времени</th>
                    <th>Количество пользователей</th>
                    <th>Удалить</th>
                </tr>
            </thead>
            <tbody>
                {% for group in groups %}
                <tr>
                    <td>{{ group.title }}</td>
                    <td>{{ group.access_for_emplyees }}</td>
                    <td>{{ group.access_for_departments }}</td>
                    <td>{{ group.access_for_jobs }}</td>
                    <td>{{ group.access_for_reports }}</td>
                    <td>{{ group.access_for_time }}</td>
                    <td>{{ group.user_set.count }}</td>
                    <td class="actions">
                        <form action="{% url 'groups' %}?delete={{ group.id }}" method="post">{% csrf_token %}<button type="submit">Удалить</button></form>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</body>
</html>